version: 1.0.{build}
build:
  verbosity: normal

image:
  - Visual Studio 2015
  - Visual Studio 2017

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

branches:
  only:
    - master

init:
  - if $(platform)==x86 (if %VISUAL_STUDIO_VERSION%==14 (set TARGET_VSENV=VS14_WIN32))
  - if $(platform)==x64 (if %VISUAL_STUDIO_VERSION%==14 (set TARGET_VSENV=VS14_WIN64))
  - if $(platform)==x86 (if %VISUAL_STUDIO_VERSION%==15 (set TARGET_VSENV=VS15_WIN32))
  - if $(platform)==x64 (if %VISUAL_STUDIO_VERSION%==15 (set TARGET_VSENV=VS15_WIN64))

install:
  - git submodule update --init
  - mkdir build
  - cd build
  - if %TARGET_VSENV%==VS14_WIN32 cmake -G "Visual Studio 14 2015" -D CMAKE_CONFIGURATION_TYPES=$(configuration) -D CMAKE_CXX_COMPILER_ID=MSVC_14 ../
  - if %TARGET_VSENV%==VS14_WIN64 cmake -G "Visual Studio 14 2015 Win64" -D CMAKE_CONFIGURATION_TYPES=$(configuration) -D CMAKE_CXX_COMPILER_ID=MSVC_14 ../
  - if %TARGET_VSENV%==VS15_WIN32 cmake -G "Visual Studio 15 2017" -D CMAKE_CONFIGURATION_TYPES=$(configuration) -D CMAKE_CXX_COMPILER_ID=MSVC_15 ../
  - if %TARGET_VSENV%==VS15_WIN64 cmake -G "Visual Studio 15 2017 Win64" -D CMAKE_CONFIGURATION_TYPES=$(configuration) -D CMAKE_CXX_COMPILER_ID=MSVC_15 ../
  - cd ..
