version: 1.0.{build}
build:
  verbosity: minimal

image:
  - Visual Studio 2015
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2017
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 2015 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 2017
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 2017 Win64

configuration:
  - Debug
  - Release

branches:
  only:
    - master

before_build:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

build_script:
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_GENERATOR%" -D CMAKE_BUILD_TYPE="DEBUG;RELEASE" -D CMAKE_CXX_COMPILER_ID=MSVC ../
