variables:
    GIT_SUBMODULE_STRATEGY: "recursive"

before_script:
    - git lfs fetch
    - git lfs checkout

after_script:
    - echo log-after_script

stages:
    - check
    - test

checked_by_cppcheck:
    stage: check
    script:
        - echo check
        - 'cppcheck . --enable=warning,style,performance,portability --xml-version=2 --error-exitcode=1 -i external/ -i build/ -i tools/'
    tags:
        - cppcheck

test_win32:
    stage: test
    script:
        - 'call "%VS140COMNTOOLS%VsDevCmd.bat"'
        - 'if exist build rmdir /s /q build'
        - 'if exist output rmdir /s /q output'
        - 'mkdir build'
        - 'cd build'
        - 'cmake -G "Visual Studio 14 2015" ../'
        - 'msbuild libgltf.sln /t:Rebuild /p:Configuration="Debug" /p:Platform="Win32"'
        - '..\output\bin\win32\Debug\runtest.exe ..\resource\example-2.0\glTF-BarramundiFish.gltf'
        - '..\output\bin\win32\Debug\runtest.exe ..\resource\example-2.0\glTF-Draco-BarramundiFish.gltf'
        - '..\output\bin\win32\Debug\runtest.exe ..\resource\example-2.0\glTF-pbrSpecularGlossinessBarramundiFish.gltf'
        - 'cd ../'
    tags:
        - win32
        - cmake
        - vs2015

test_win64:
    stage: test
    script:
        - 'call "%VS140COMNTOOLS%VsDevCmd.bat"'
        - 'if exist build rmdir /s /q build'
        - 'if exist output rmdir /s /q output'
        - 'mkdir build'
        - 'cd build'
        - 'cmake -G "Visual Studio 14 2015 Win64" ../'
        - 'msbuild libgltf.sln /t:Rebuild /p:Configuration="Debug" /p:Platform="x64"'
        - '..\output\bin\win64\Debug\runtest.exe ..\resource\example-2.0\glTF-BarramundiFish.gltf'
        - '..\output\bin\win64\Debug\runtest.exe ..\resource\example-2.0\glTF-Draco-BarramundiFish.gltf'
        - '..\output\bin\win64\Debug\runtest.exe ..\resource\example-2.0\glTF-pbrSpecularGlossinessBarramundiFish.gltf'
        - 'cd ../'
    tags:
        - win64
        - cmake
        - vs2015

test_linux:
    stage: test
    script:
        - 'mkdir build'
        - 'cd build'
        - 'cmake -DCMAKE_BUILD_TYPE=Debug -DLIBGLTF_BUILD_GCOV=TRUE -G "Unix Makefiles" ../'
        - 'make'
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls'
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls ../resource/nothing.gltf'
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls ../resource/example-2.0/glTF-BarramundiFish.gltf'
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls ../resource/example-2.0/glTF-Draco-BarramundiFish.gltf'
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls ../resource/example-2.0/glTF-pbrSpecularGlossinessBarramundiFish.gltf'
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls ../resource/example-2.0/AnimatedMorphCube.gltf'
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls ../resource/example-2.0/BoxAnimated.gltf'
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls ../resource/example-2.0/Cameras.gltf'
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls ../resource/example-2.0/DamagedHelmet.Embedded.gltf'
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls ../resource/example-2.0/RiggedSimple.gltf'
        - 'gcov source/runtest/CMakeFiles/runtest.dir/runtest.cpp.gcda'
        - 'gcovr --root=../source/ .'
        - 'cd ../'
    tags:
        - linux
        - cmake
        - make
        - valgrind
        - gcc
        - gcovr

test_macos:
    stage: test
    script:
        - 'mkdir build'
        - 'cd build'
        - 'cmake -G "Unix Makefiles" ../'
        - 'make'
        - './../output/bin/macos/runtest ../resource/example-2.0/glTF-BarramundiFish.gltf'
        - './../output/bin/macos/runtest ../resource/example-2.0/glTF-Draco-BarramundiFish.gltf'
        - './../output/bin/macos/runtest ../resource/example-2.0/glTF-pbrSpecularGlossinessBarramundiFish.gltf'
        - 'cd ../'
    tags:
        - macos
        - cmake
        - make
        - gcc
