variables:
    GIT_SUBMODULE_STRATEGY: "recursive"

before_script:
    - git lfs fetch
    - git lfs checkout

after_script:
    - echo log-after_script

stages:
    - check
    - test
    - build
    - package
    - deploy

checked_by_cppcheck:
    stage: check
    script:
        - echo check
        - 'cppcheck . --enable=warning,style,performance,portability --xml-version=2 --error-exitcode=1 -i external/ -i build/ -i tools/'
    tags:
        - cppcheck

test_win32:
    stage: test
    script:
        - 'call "%VS140COMNTOOLS%VsDevCmd.bat"'
        - if exist build rmdir /s /q build
        - if exist output rmdir /s /q output
        - mkdir build
        - cd build
        - 'cmake -G "Visual Studio 14 2015" ../'
        - 'msbuild libgltf.sln /t:Rebuild /p:Configuration="Debug" /p:Platform="Win32"'
        - '..\output\bin\win32\Debug\runtest.exe ..\resource\example-2.0\BarramundiFish.gltf'
        - cd ../
    tags:
        - win32
        - cmake
        - vs2015

test_win64:
    stage: test
    script:
        - 'call "%VS140COMNTOOLS%VsDevCmd.bat"'
        - if exist build rmdir /s /q build
        - if exist output rmdir /s /q output
        - mkdir build
        - cd build
        - 'cmake -G "Visual Studio 14 2015 Win64" ../'
        - 'msbuild libgltf.sln /t:Rebuild /p:Configuration="Debug" /p:Platform="x64"'
        - '..\output\bin\win64\Debug\runtest.exe ..\resource\example-2.0\BarramundiFish.gltf'
        - cd ../
    tags:
        - win64
        - cmake
        - vs2015

test_linux:
    stage: test
    script:
        - mkdir build
        - cd build
        - 'cmake -DLIBGLTF_BUILD_GCOV=TRUE -G "Unix Makefiles" ../'
        - make
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls ../resource/example-2.0/AnimatedMorphCube.gltf'
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls ../resource/example-2.0/BarramundiFish.gltf'
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls ../resource/example-2.0/BoxAnimated.gltf'
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls ../resource/example-2.0/Cameras.gltf'
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls ../resource/example-2.0/DamagedHelmet.Embedded.gltf'
        - 'valgrind --leak-check=full --show-leak-kinds=all ./../output/bin/linux/runtest --coveralls ../resource/example-2.0/RiggedSimple.gltf'
        - gcov source/runtest/CMakeFiles/runtest.dir/runtest.cpp.gcda
        - gcovr --root=../source/ .
        - cd ../
    tags:
        - linux
        - cmake
        - make
        - valgrind
        - gcc
        - gcovr

test_macos:
    stage: test
    script:
        - mkdir build
        - cd build
        - 'cmake -G "Unix Makefiles" ../'
        - make
        - './../output/bin/macos/runtest --coveralls ../resource/example-2.0/BarramundiFish.gltf'
        - cd ../
    tags:
        - macos
        - cmake
        - make
        - gcc

build_win32:
    stage: build
    script:
        - 'call "%VS140COMNTOOLS%VsDevCmd.bat"'
        - if exist build rmdir /s /q build
        - if exist output rmdir /s /q output
        - mkdir build
        - cd build
        - 'cmake -G "Visual Studio 14 2015" ../'
        - 'msbuild libgltf.sln /t:Rebuild /p:Configuration="Release" /p:Platform="Win32"'
        - cd ../
    artifacts:
        name: "libgltf_win32.%CI_PIPELINE_ID%.%CI_JOB_ID%"
        expire_in: 2 days
        paths:
            - output/include/*
            - output/lib/**/*.lib
            - output/lib/**/**/*.lib
    when: manual
    tags:
        - win32
        - cmake
        - vs2015

build_win64:
    stage: build
    script:
        - 'call "%VS140COMNTOOLS%VsDevCmd.bat"'
        - if exist build rmdir /s /q build
        - if exist output rmdir /s /q output
        - mkdir build
        - cd build
        - 'cmake -G "Visual Studio 14 2015 Win64" ../'
        - 'msbuild libgltf.sln /t:Rebuild /p:Configuration="Release" /p:Platform="x64"'
        - cd ../
    artifacts:
        name: "libgltf_win64.%CI_PIPELINE_ID%.%CI_JOB_ID%"
        expire_in: 2 days
        paths:
            - output/include/*
            - output/lib/**/*.lib
            - output/lib/**/**/*.lib
    when: manual
    tags:
        - win64
        - cmake
        - vs2015

build_linux:
    stage: build
    script:
        - mkdir build
        - cd build
        - 'cmake -G "Unix Makefiles" ../'
        - make
        - cd ../
    artifacts:
        name: "libgltf_linux.${CI_PIPELINE_ID}.${CI_JOB_ID}"
        expire_in: 2 days
        paths:
            - output/include/*
            - output/lib/**/*.a
    when: manual
    tags:
        - linux
        - cmake
        - make
        - gcc

build_macos:
    stage: build
    script:
        - mkdir build
        - cd build
        - 'cmake -G "Unix Makefiles" ../'
        - make
        - cd ../
    artifacts:
        name: "libgltf_macos.${CI_PIPELINE_ID}.${CI_JOB_ID}"
        expire_in: 2 days
        paths:
            - output/include/*
            - output/lib/**/*.a
    when: manual
    tags:
        - macos
        - cmake
        - make
        - gcc

package_all:
    stage: package
    script:
        - 'echo package_all'
    dependencies:
        - build_win32
        - build_win64
        - build_macos
        - build_linux
    artifacts:
        name: "libgltf.%CI_PIPELINE_ID%.%CI_JOB_ID%"
        expire_in: 1 week
        paths:
            - output/include/**/*
            - output/lib/**/*
    when: manual
    tags:
        - win64
