language: cpp

sudo: required

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9

script:
  - set -e
  - mkdir ./build && cd ./build
  - cmake ./../
  - make
  - cd ./../

branches:
  only:
    - master
