language: cpp

sudo: required

matrix:
  include:
    # Linux
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    # Mac OSX
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

install:
  - echo $LANG
  - echo $LC_ALL

script:
  - set -e
  - mkdir ./build; cd ./build
  - cmake ./../
  - make
  - cd ./../

branches:
  only:
    - master
