language: cpp

sudo: required

matrix:
  include:
    - os: linux
      env:
        - RUN_COVERALLS=false
    - os: linux
      env:
        - RUN_COVERALLS=true
    - os: osx
      env:
        - RUN_COVERALLS=false

branches:
  only:
    - master

install:
  - sudo pip install cpp-coveralls
  - if [ $TRAVIS_OS_NAME == osx ]; then unset -f cd; fi

script:
  - set -e
  - mkdir ./build && cd ./build
  - if [ "$RUN_COVERALLS"x = "false"x ]; then cmake ./../; fi
  - if [ "$RUN_COVERALLS"x = "true"x ]; then cmake -D LIBGLTF_COVERAGE_GCOV=TRUE ./../; fi
  - make
  - cd ./../

after_success:
  - if [ "$RUN_COVERALLS"x = "true"x ]; then ./output/bin/linux/runtest; fi
  - if [ "$RUN_COVERALLS"x = "true"x ]; then coveralls --exclude build/ --gcov-options '\-lp'; fi
