jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    lfs: true
    submodules: true
    displayName: "Pull all repos"
  - script: |
      mkdir build
      cd build
      cmake -G "Unix Makefiles" ../
      make libgltf
      cd ../
    displayName: "Compile for Linux"

- job: macos
  pool:
    vmImage: 'macOS-latest'
  steps:
  - checkout: self
    lfs: true
    submodules: true
    displayName: "Pull all repos"
  - script: |
      mkdir build
      cd build
      cmake -G "Unix Makefiles" ../
      make libgltf
      cd ../
    displayName: "Compile for macOS"

- job: vs2019_x32
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
    lfs: true
    submodules: true
    displayName: "Pull all repos"
  - script: |
      mkdir build
      cd build
      cmake -G "Visual Studio 16 2019" -A "Win32" -DLIBGLTF_CHARACTOR_ENCODING=UTF8 ../
      cd ../
    displayName: "CMake for VS2019 Win32"
  - task: MSBuild@1
    inputs:
      solution: build/libgltf.sln
      msbuildVersion: latest
      msbuildArchitecture: x32
      platform: Win32
      configuration: Release
      displayName: "Compile for VS2019 Win32"

- job: vs2019_x64
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
    lfs: true
    submodules: true
    displayName: "Pull all repos"
  - script: |
      mkdir build
      cd build
      cmake -G "Visual Studio 16 2019" -A "x64" -DLIBGLTF_CHARACTOR_ENCODING=UTF8 ../
      cd ../
    displayName: "CMake for VS2019 x64"
  - task: MSBuild@1
    inputs:
      solution: build/libgltf.sln
      msbuildVersion: latest
      msbuildArchitecture: x64
      platform: x64
      configuration: Release
      displayName: "Compile for VS2019 x64"
