jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      mkdir build
      cd build
      cmake -G "Unix Makefiles" ../
      make libgltf
      cd ../
    displayName: "Compile for Linux"
  - checkout: self
    lfs: true
    submodules: true

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
      mkdir build
      cd build
      cmake -G "Unix Makefiles" ../
      make libgltf
      cd ../
    displayName: "Compile for macOS"
  - checkout: self
    lfs: true
    submodules: true
