jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      mkdir build
      cd build
      cmake -G "Unix Makefiles" ../
      make libgltf
      cd ../

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
      mkdir build
      cd build
      cmake -G "Unix Makefiles" ../
      make libgltf
      cd ../
