# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

jobs:
- job: Linux

  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - script: |
      mkdir build
      cd build
      cmake -G "Unix Makefiles" ../
      make libgltf
      cd ../

jobs:
- job: macOS

  pool:
    vmImage: 'macOS 11'

  steps:
  - script: |
      mkdir build
      cd build
      cmake -G "Unix Makefiles" ../
      make libgltf
      cd ../
