name: 'build'

on:
  push:
    branches: [ '*' ]
    paths-ignore:
    - '!.github/build.yml'
    - 'docs/**'
    - 'resource/**'
    - '.coveralls.yml'
    - '.readthedocs.yml'
    - '.git*'
    - '*.md'
    - 'LICENSE'

jobs:
  check:
    name: 'check by cppcheck'
    runs-on: ubuntu-latest
    steps:
    - name: 'install cppcheck'
      run: sudo apt-get install cppcheck
    - name: 'checkout'
      uses: actions/checkout@v2
    - name: 'check'
      run: cppcheck ./ --enable=warning,performance,portability --xml-version=2 --error-exitcode=1 -i external/ -i build/ -i tools/
  windows:
    name: 'for windows'
    runs-on: windows-latest
    needs: check
    steps:
    - name: 'checkout the project'
      uses: actions/checkout@v2
    - name: 'update submodules'
      run: |
        git submodule update --init external/rapidjson
        git submodule update --init external/draco
    - name: 'add msbuild'
      uses: microsoft/setup-msbuild@v1.0.2
    - name: 'build and make'
      run: |
        cmake -B build/win64 -G "Visual Studio 16 2019" -A "x64" -DLIBGLTF_BUILD_MSVC_WITH_MT=FALSE -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_USE_GOOGLE_DRACO=TRUE .
        cmake --build build/win64 --target libgltf --config Debug
        cmake --build build/win64 --target libgltf --config Release
        cmake -B build/win32 -G "Visual Studio 16 2019" -A "Win32" -DLIBGLTF_BUILD_MSVC_WITH_MT=FALSE -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_USE_GOOGLE_DRACO=TRUE .
        cmake --build build/win32 --target libgltf --config Debug
        cmake --build build/win32 --target libgltf --config Release
    - name: 'ready artifact'
      run: |
        xcopy /D /S /Y build\win64\draco\*.h output\include\draco\
        xcopy /D /S /Y external\draco\src\draco\*.h output\include\draco\
        xcopy /D /S /Y build\win64\external\draco\Release\draco.lib output\lib\win64\Release\
        xcopy /D /S /Y build\win64\external\draco\Release\draco_core.lib output\lib\win64\Release\
        xcopy /D /S /Y build\win64\external\draco\Debug\dracod.lib output\lib\win64\Debug\
        xcopy /D /S /Y build\win64\external\draco\Debug\draco_cored.lib output\lib\win64\Debug\
        xcopy /D /S /Y build\win32\external\draco\Release\draco.lib output\lib\win32\Release\
        xcopy /D /S /Y build\win32\external\draco\Release\draco_core.lib output\lib\win32\Release\
        xcopy /D /S /Y build\win32\external\draco\Debug\dracod.lib output\lib\win32\Debug\
        xcopy /D /S /Y build\win32\external\draco\Debug\draco_cored.lib output\lib\win32\Debug\
    - name: 'upload artifact'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: libgltf.windows
        path: output/

  linux:
    name: 'for linux'
    runs-on: ubuntu-latest
    needs: check
    steps:
    - name: 'checkout the project'
      uses: actions/checkout@v2
    - name: 'update submodules'
      run: |
        git submodule update --init external/rapidjson
        git submodule update --init external/draco
    - name: 'build and make'
      run: |
        cmake -B build -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_USE_GOOGLE_DRACO=TRUE .
        cmake --build build --target libgltf --config Release
    - name: 'ready artifact'
      run: |
        rsync -a --include='*.h' -f 'hide,! */' build/draco/ output/include/draco/
        rsync -a --include='*.h' -f 'hide,! */' external/draco/src/draco/ output/include/draco/
        cp -a build/external/draco/draco.a output/lib/linux/draco.a
        cp -a build/external/draco/draco_core.a output/lib/linux/draco_core.a
    - name: 'upload artifact'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: libgltf.linux
        path: output/

  macos:
    name: 'for macos'
    runs-on: macos-latest
    needs: check
    steps:
    - name: 'checkout the project'
      uses: actions/checkout@v2
    - name: 'update submodules'
      run: |
        git submodule update --init external/rapidjson
        git submodule update --init external/draco
    - name: 'build and make'
      run: |
        cmake -B build -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_USE_GOOGLE_DRACO=TRUE .
        cmake --build build --target libgltf --config Release
    - name: 'ready artifact'
      run: |
        rsync -a --include='*.h' -f 'hide,! */' build/draco/ output/include/draco/
        rsync -a --include='*.h' -f 'hide,! */' external/draco/src/draco/ output/include/draco/
        cp build/external/draco/draco.a output/lib/macos/draco.a
        cp build/external/draco/draco_core.a output/lib/macos/draco_core.a
    - name: 'upload artifact'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: libgltf.macos
        path: output/

  android:
    name: 'for android api19'
    runs-on: ubuntu-latest
    needs: check
    steps:
    - name: 'install'
      run: |
        sudo apt-get install ninja-build
    - name: 'checkout the project'
      uses: actions/checkout@v2
    - name: 'update submodules'
      run: |
        git submodule update --init external/rapidjson
        git submodule update --init external/draco
    - name: 'build and make'
      run: |
        export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
        cmake -B build/armeabi-v7a -G "Ninja" -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_ARM_NEON=FALSE -DANDROID_NDK=$ANDROID_NDK_HOME -DANDROID_NATIVE_API_LEVEL=19 -DANDROID_TOOLCHAIN=clang -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_CHARACTOR_ENCODING=UTF8 -DLIBGLTF_USE_GOOGLE_DRACO=TRUE .
        cmake --build build/armeabi-v7a --target libgltf --config Release
        cmake -B build/armeabi-v7a-with-neon -G "Ninja" -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_ARM_NEON=TRUE -DANDROID_NDK=$ANDROID_NDK_HOME -DANDROID_NATIVE_API_LEVEL=19 -DANDROID_TOOLCHAIN=clang -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_CHARACTOR_ENCODING=UTF8 -DLIBGLTF_USE_GOOGLE_DRACO=TRUE .
        cmake --build build/armeabi-v7a-with-neon --target libgltf --config Release
        cmake -B build/arm64-v8a -G "Ninja" -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_ARM_NEON=FALSE -DANDROID_NDK=$ANDROID_NDK_HOME -DANDROID_NATIVE_API_LEVEL=19 -DANDROID_TOOLCHAIN=clang -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_CHARACTOR_ENCODING=UTF8 -DLIBGLTF_USE_GOOGLE_DRACO=TRUE .
        cmake --build build/arm64-v8a --target libgltf --config Release
        cmake -B build/x86 -G "Ninja" -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=x86 -DANDROID_ARM_NEON=FALSE -DANDROID_NDK=$ANDROID_NDK_HOME -DANDROID_NATIVE_API_LEVEL=19 -DANDROID_TOOLCHAIN=clang -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_CHARACTOR_ENCODING=UTF8 -DLIBGLTF_USE_GOOGLE_DRACO=TRUE .
        cmake --build build/x86 --target libgltf --config Release
        cmake -B build/x86_64 -G "Ninja" -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=x86_64 -DANDROID_ARM_NEON=FALSE -DANDROID_NDK=$ANDROID_NDK_HOME -DANDROID_NATIVE_API_LEVEL=19 -DANDROID_TOOLCHAIN=clang -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_CHARACTOR_ENCODING=UTF8 -DLIBGLTF_USE_GOOGLE_DRACO=TRUE .
        cmake --build build/x86_64 --target libgltf --config Release
    - name: 'ready artifact'
      run: |
        rsync -a --include='*.h' -f 'hide,! */' external/draco/src/draco/ output/include/draco/
        rsync -a --include='*.h' -f 'hide,! */' build/armeabi-v7a/draco/ output/include/draco/
        cp -a build/armeabi-v7a/external/draco/draco.a output/lib/android/armeabi-v7a/draco.a
        cp -a build/armeabi-v7a/external/draco/draco_core.a output/lib/android/armeabi-v7a/draco_core.a
        cp -a build/armeabi-v7a-with-neon/external/draco/draco.a output/lib/android/armeabi-v7a-with-neon/draco.a
        cp -a build/armeabi-v7a-with-neon/external/draco/draco_core.a output/lib/android/armeabi-v7a-with-neon/draco_core.a
        cp -a build/arm64-v8a/external/draco/draco.a output/lib/android/arm64-v8a/draco.a
        cp -a build/arm64-v8a/external/draco/draco_core.a output/lib/android/arm64-v8a/draco_core.a
        cp -a build/x86/external/draco/draco.a output/lib/android/x86/draco.a
        cp -a build/x86/external/draco/draco_core.a output/lib/android/x86/draco_core.a
        cp -a build/x86_64/external/draco/draco.a output/lib/android/x86_64/draco.a
        cp -a build/x86_64/external/draco/draco_core.a output/lib/android/x86_64/draco_core.a
    - name: 'upload artifact'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: libgltf.android.api19
        path: output/

  ios:
    name: 'for ios'
    runs-on: macos-latest
    needs: check
    steps:
    - name: 'checkout the project'
      uses: actions/checkout@v2
    - name: 'update submodules'
      run: |
        git submodule update --init external/rapidjson
        git submodule update --init external/draco
        git submodule update --init external/ios-cmake
    - name: 'build and make'
      run: |
        cmake -B build/iphoneos -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../external/ios-cmake/toolchain/iOS.cmake -DLIBGLTF_BUILD_RUNTEST=FALSE -DIOS_PLATFORM=OS -DLIBGLTF_PLATFORM_IOS=TRUE -DLIBGLTF_CHARACTOR_ENCODING=UTF8 -DLIBGLTF_USE_GOOGLE_DRACO=TRUE .
        cmake --build build/iphoneos --target libgltf --config Release
        cmake -B build/watchos -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../external/ios-cmake/toolchain/iOS.cmake -DIOS_PLATFORM=WATCHOS -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_PLATFORM_IOS=TRUE -DLIBGLTF_CHARACTOR_ENCODING=UTF8 -DLIBGLTF_USE_GOOGLE_DRACO=TRUE .
        cmake --build build/watchos --target libgltf --config Release
        cmake -B build/simulator -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../external/ios-cmake/toolchain/iOS.cmake -DIOS_PLATFORM=SIMULATOR -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_PLATFORM_IOS=TRUE -DLIBGLTF_CHARACTOR_ENCODING=UTF8 -DLIBGLTF_USE_GOOGLE_DRACO=TRUE .
        cmake --build build/simulator --target libgltf --config Release
    - name: 'ready artifact'
      run: |
        rsync -a --include='*.h' -f 'hide,! */' external/draco/src/draco/ output/include/draco/
        rsync -a --include='*.h' -f 'hide,! */' build/iphoneos/draco/ output/include/draco/
        cp build/iphoneos/external/draco/draco.a output/lib/ios/os/draco.a
        cp build/iphoneos/external/draco/draco_core.a output/lib/ios/os/draco_core.a
        cp build/watchos/external/draco/draco.a output/lib/ios/watchos/draco.a
        cp build/watchos/external/draco/draco_core.a output/lib/ios/watchos/draco_core.a
        cp build/simulator/external/draco/draco.a output/lib/ios/simulator/draco.a
        cp build/simulator/external/draco/draco_core.a output/lib/ios/simulator/draco_core.a
    - name: 'upload artifact'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: libgltf.ios
        path: output/
