name: 'build develop'

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  linux:
    name: 'for linux'
    runs-on: ubuntu-latest
    steps:
    - name: 'test'
      run: |
        echo $ANDROID_NDK_HOME
  macos:
    name: 'for macos'
    runs-on: macos-latest
    steps:
    - name: 'test'
      run: |
        echo $ANDROID_NDK_HOME
  windows:
    name: 'for windows'
    runs-on: windows-latest
    steps:
    - name: 'test'
      run: |
        echo %ANDROID_NDK_HOME%
