name: 'build develop'

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  windows_win64:
    name: 'for windows win64'
    runs-on: windows-latest
    steps:
    - name: 'checkout the project'
      uses: actions/checkout@v2
    - name: 'update submodules'
      run: |
        git submodule update --init external/rapidjson
        git submodule update --init external/draco
    - name: 'add msbuild'
      uses: microsoft/setup-msbuild@v1.0.2
    - name: 'build and make'
      run: |
        mkdir build && cd build/
        mkdir win64 && cd win64/
        cmake -G "Visual Studio 16 2019" -A "x64" -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_USE_GOOGLE_DRACO=TRUE -DLIBGLTF_USE_GOOGLE_DRACO_SUBMODULE=TRUE ../../
        msbuild libgltf.sln /t:Build /p:Configuration="Release" /p:Platform="x64"
        cd ../
        cd ../
    - name: 'ready artifact'
      run: |
        xcopy /D /S /Y external\draco\src\draco\*.h output\include\draco\
        xcopy /D /S /Y build\win64\draco\*.h output\include\draco\
        xcopy /D /S /Y build\win64\external\draco\Release\*.lib output\lib\win64\Release\
    - name: 'upload artifact'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: libgltf.win64.windows
        path: output/
