name: 'release'

on:
  push:
    tags: [ '*' ]
    paths-ignore:
    - '!.github/release.yml'
    - 'docs/**'
    - 'resource/**'
    - '.coveralls.yml'
    - '.readthedocs.yml'
    - '.git*'
    - '*.md'
    - 'LICENSE'

jobs:
  check:
    name: 'check by cppcheck'
    runs-on: ubuntu-latest
    steps:
    - name: 'install cppcheck'
      run: sudo apt-get install cppcheck
    - name: 'checkout'
      uses: actions/checkout@v2
    - name: 'check'
      run: cppcheck ./ --enable=warning,performance,portability --xml-version=2 --error-exitcode=1 -i external/ -i build/ -i tools/
  windows:
    name: 'for windows'
    runs-on: windows-latest
    needs: check
    steps:
    - name: 'checkout the project'
      uses: actions/checkout@v2
    - name: 'update submodules'
      run: |
        git submodule update --init external/rapidjson
        git submodule update --init external/draco
    - name: 'add msbuild'
      uses: microsoft/setup-msbuild@v1.0.2
    - name: 'build and make'
      run: |
        cmake -B build/win64 -G "Visual Studio 16 2019" -A "x64" -DLIBGLTF_WITH_MSVC_MT=FALSE -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_WITH_GOOGLE_DRACO=TRUE .
        cmake --build build/win64 --target libgltf --config Debug
        cmake --build build/win64 --target libgltf --config Release
        cmake -B build/win32 -G "Visual Studio 16 2019" -A "Win32" -DLIBGLTF_WITH_MSVC_MT=FALSE -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_WITH_GOOGLE_DRACO=TRUE .
        cmake --build build/win32 --target libgltf --config Debug
        cmake --build build/win32 --target libgltf --config Release
    - name: 'ready artifact'
      run: |
        xcopy /D /S /Y build\win64\draco\*.h build\include\draco\
        xcopy /D /S /Y external\draco\src\draco\*.h build\include\draco\
        xcopy /D /S /Y build\win64\external\draco\Release\draco.lib build\lib\win64\Release\
        xcopy /D /S /Y build\win64\external\draco\Release\draco_core.lib build\lib\win64\Release\
        xcopy /D /S /Y build\win64\external\draco\Debug\dracod.lib build\lib\win64\Debug\
        xcopy /D /S /Y build\win64\external\draco\Debug\draco_cored.lib build\lib\win64\Debug\
        xcopy /D /S /Y build\win32\external\draco\Release\draco.lib build\lib\win32\Release\
        xcopy /D /S /Y build\win32\external\draco\Release\draco_cored.lib build\lib\win32\Release\
        xcopy /D /S /Y build\win32\external\draco\Debug\dracod.lib build\lib\win32\Debug\
        xcopy /D /S /Y build\win32\external\draco\Debug\draco_cored.lib build\lib\win32\Debug\
    - name: 'upload artifact'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: libgltf.windows
        path: output/

  linux:
    name: 'for linux'
    runs-on: ubuntu-latest
    needs: check
    steps:
    - name: 'checkout the project'
      uses: actions/checkout@v2
    - name: 'update submodules'
      run: |
        git submodule update --init external/rapidjson
        git submodule update --init external/draco
    - name: 'build and make'
      run: |
        cmake -B build -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_WITH_GOOGLE_DRACO=TRUE .
        cmake --build build --target libgltf --config Release
    - name: 'ready artifact'
      run: |
        rsync -a --include='*.h' -f 'hide,! */' build/draco/ build/include/draco/
        rsync -a --include='*.h' -f 'hide,! */' external/draco/src/draco/ build/include/draco/
        cp -a build/external/draco/draco.a build/lib/linux/draco.a
        cp -a build/external/draco/draco_core.a build/lib/linux/draco_core.a
    - name: 'upload artifact'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: libgltf.linux
        path: output/

  macos:
    name: 'for macos'
    runs-on: macos-latest
    needs: check
    steps:
    - name: 'checkout the project'
      uses: actions/checkout@v2
    - name: 'update submodules'
      run: |
        git submodule update --init external/rapidjson
        git submodule update --init external/draco
    - name: 'build and make'
      run: |
        cmake -B build -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_WITH_GOOGLE_DRACO=TRUE .
        cmake --build build --target libgltf --config Release
    - name: 'ready artifact'
      run: |
        rsync -a --include='*.h' -f 'hide,! */' build/draco/ build/include/draco/
        rsync -a --include='*.h' -f 'hide,! */' external/draco/src/draco/ build/include/draco/
        cp build/external/draco/draco.a build/lib/macos/draco.a
        cp build/external/draco/draco_core.a build/lib/macos/draco_core.a
    - name: 'upload artifact'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: libgltf.macos
        path: output/

  android:
    name: 'for android api19'
    runs-on: ubuntu-latest
    needs: check
    steps:
    - name: 'install'
      run: |
        sudo apt-get install ninja-build
    - name: 'checkout the project'
      uses: actions/checkout@v2
    - name: 'update submodules'
      run: |
        git submodule update --init external/rapidjson
        git submodule update --init external/draco
    - name: 'build and make'
      run: |
        export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
        cmake -B build/armeabi-v7a -G "Ninja" -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_ARM_NEON=FALSE -DANDROID_NDK=$ANDROID_NDK_HOME -DANDROID_NATIVE_API_LEVEL=19 -DANDROID_TOOLCHAIN=clang -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_WITH_GOOGLE_DRACO=TRUE .
        cmake --build build/armeabi-v7a --target libgltf --config Release
        cmake -B build/armeabi-v7a-with-neon -G "Ninja" -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_ARM_NEON=TRUE -DANDROID_NDK=$ANDROID_NDK_HOME -DANDROID_NATIVE_API_LEVEL=19 -DANDROID_TOOLCHAIN=clang -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_WITH_GOOGLE_DRACO=TRUE .
        cmake --build build/armeabi-v7a-with-neon --target libgltf --config Release
        cmake -B build/arm64-v8a -G "Ninja" -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_ARM_NEON=FALSE -DANDROID_NDK=$ANDROID_NDK_HOME -DANDROID_NATIVE_API_LEVEL=19 -DANDROID_TOOLCHAIN=clang -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_WITH_GOOGLE_DRACO=TRUE .
        cmake --build build/arm64-v8a --target libgltf --config Release
        cmake -B build/x86 -G "Ninja" -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=x86 -DANDROID_ARM_NEON=FALSE -DANDROID_NDK=$ANDROID_NDK_HOME -DANDROID_NATIVE_API_LEVEL=19 -DANDROID_TOOLCHAIN=clang -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_WITH_GOOGLE_DRACO=TRUE .
        cmake --build build/x86 --target libgltf --config Release
        cmake -B build/x86_64 -G "Ninja" -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=x86_64 -DANDROID_ARM_NEON=FALSE -DANDROID_NDK=$ANDROID_NDK_HOME -DANDROID_NATIVE_API_LEVEL=19 -DANDROID_TOOLCHAIN=clang -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_WITH_GOOGLE_DRACO=TRUE .
        cmake --build build/x86_64 --target libgltf --config Release
    - name: 'ready artifact'
      run: |
        rsync -a --include='*.h' -f 'hide,! */' external/draco/src/draco/ build/include/draco/
        rsync -a --include='*.h' -f 'hide,! */' build/armeabi-v7a/draco/ build/include/draco/
        cp -a build/armeabi-v7a/external/draco/draco.a build/lib/android/armeabi-v7a/draco.a
        cp -a build/armeabi-v7a/external/draco/draco_core.a build/lib/android/armeabi-v7a/draco_core.a
        cp -a build/armeabi-v7a-with-neon/external/draco/draco.a build/lib/android/armeabi-v7a-with-neon/draco.a
        cp -a build/armeabi-v7a-with-neon/external/draco/draco_core.a build/lib/android/armeabi-v7a-with-neon/draco_core.a
        cp -a build/arm64-v8a/external/draco/draco.a build/lib/android/arm64-v8a/draco.a
        cp -a build/arm64-v8a/external/draco/draco_core.a build/lib/android/arm64-v8a/draco_core.a
        cp -a build/x86/external/draco/draco.a build/lib/android/x86/draco.a
        cp -a build/x86/external/draco/draco_core.a build/lib/android/x86/draco_core.a
        cp -a build/x86_64/external/draco/draco.a build/lib/android/x86_64/draco.a
        cp -a build/x86_64/external/draco/draco_core.a build/lib/android/x86_64/draco_core.a
    - name: 'upload artifact'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: libgltf.android.api19
        path: output/

  ios:
    name: 'for ios'
    runs-on: macos-latest
    needs: check
    steps:
    - name: 'checkout the project'
      uses: actions/checkout@v2
    - name: 'update submodules'
      run: |
        git submodule update --init external/rapidjson
        git submodule update --init external/draco
        git submodule update --init external/ios-cmake
    - name: 'build and make'
      run: |
        cmake -B build/iphoneos -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../external/ios-cmake/toolchain/iOS.cmake -DLIBGLTF_BUILD_RUNTEST=FALSE -DIOS_PLATFORM=OS -DLIBGLTF_PLATFORM_IOS=TRUE -DLIBGLTF_WITH_GOOGLE_DRACO=TRUE .
        cmake --build build/iphoneos --target libgltf --config Release
        cmake -B build/watchos -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../external/ios-cmake/toolchain/iOS.cmake -DIOS_PLATFORM=WATCHOS -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_PLATFORM_IOS=TRUE -DLIBGLTF_WITH_GOOGLE_DRACO=TRUE .
        cmake --build build/watchos --target libgltf --config Release
        cmake -B build/simulator -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../external/ios-cmake/toolchain/iOS.cmake -DIOS_PLATFORM=SIMULATOR -DLIBGLTF_BUILD_RUNTEST=FALSE -DLIBGLTF_PLATFORM_IOS=TRUE -DLIBGLTF_WITH_GOOGLE_DRACO=TRUE .
        cmake --build build/simulator --target libgltf --config Release
    - name: 'ready artifact'
      run: |
        rsync -a --include='*.h' -f 'hide,! */' external/draco/src/draco/ build/include/draco/
        rsync -a --include='*.h' -f 'hide,! */' build/iphoneos/draco/ build/include/draco/
        cp build/iphoneos/external/draco/draco.a build/lib/ios/os/draco.a
        cp build/iphoneos/external/draco/draco_core.a build/lib/ios/os/draco_core.a
        cp build/watchos/external/draco/draco.a build/lib/ios/watchos/draco.a
        cp build/watchos/external/draco/draco_core.a build/lib/ios/watchos/draco_core.a
        cp build/simulator/external/draco/draco.a build/lib/ios/simulator/draco.a
        cp build/simulator/external/draco/draco_core.a build/lib/ios/simulator/draco_core.a
    - name: 'upload artifact'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: libgltf.ios
        path: output/

  release:
    name: 'release'
    runs-on: ubuntu-latest
    needs: [ windows, linux, macos, android, ios ]
    steps:
    - name: 'get version by tag'
      id: get_version
      uses: battila7/get-version-action@v2
    - name: 'create release'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: '${{ github.ref }}'
        release_name: 'Release v${{ github.ref }}'
        body: ''
        draft: false
        prerelease: false
    - name: 'download artifact'
      uses: actions/download-artifact@v2
      with:
        path: 'output/'
    - name: 'package release asset'
      run: |
        cd libgltf.windows/ && zip -r package.zip ./* && cd ../
        cd libgltf.linux/ && zip -r package.zip ./* && cd ../
        cd libgltf.macos/ && zip -r package.zip ./* && cd ../
        cd libgltf.android.api19/ && zip -r package.zip ./* && cd ../
        cd libgltf.ios/ && zip -r package.zip ./* && cd ../
      working-directory: 'output/'
    - name: 'upload release asset windows'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: 'output/libgltf.windows/package.zip'
        asset_name: 'libgltf.v${{ steps.get_version.outputs.version }}.windows.zip'
        asset_content_type: application/zip
    - name: 'upload release asset linux'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: 'output/libgltf.linux/package.zip'
        asset_name: 'libgltf.v${{ steps.get_version.outputs.version }}.linux.zip'
        asset_content_type: application/zip
    - name: 'upload release asset macos'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: 'output/libgltf.macos/package.zip'
        asset_name: 'libgltf.v${{ steps.get_version.outputs.version }}.macos.zip'
        asset_content_type: application/zip
    - name: 'upload release asset android api19'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: 'output/libgltf.android.api19/package.zip'
        asset_name: 'libgltf.v${{ steps.get_version.outputs.version }}.android.api19.zip'
        asset_content_type: application/zip
    - name: 'upload release asset ios'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: 'output/libgltf.ios/package.zip'
        asset_name: 'libgltf.v${{ steps.get_version.outputs.version }}.ios.zip'
        asset_content_type: application/zip
